name: Run tests on PRs

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  tests:
   runs-on: ubuntu-latest

   steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
       node-version: 14.21.3
       useLockFile: false
    - run: npm install
    - run: npm install     
    - run: npm test
